### ISSUE TITLE
Miscellaneous clang warnings 

### ISSUE THREAD

**Issue by mlctrez** [connornishijima/SensoryBridge#13]
Some various warnings when porting this to esp-idf v5.0-rc1.

https://github.com/connornishijima/SensoryBridge/blob/43f3bf29ab7f229771669331037268d6427e105a/SENSORY_BRIDGE_FIRMWARE/serial_menu.h#L95
```text
'memset' used with constant zero length parameter; this could be due to transposed parameters
```
https://github.com/connornishijima/SensoryBridge/blob/43f3bf29ab7f229771669331037268d6427e105a/SENSORY_BRIDGE_FIRMWARE/fft_parser.h#L12-L17
```text
warning: variable 'right_val' set but not used
which implies that left_val can also be removed
```

**Comment by connornishijima** [comment]
Fixed in https://github.com/connornishijima/SensoryBridge/commit/26d3ebba74e1aefc431b3246cc72febecdb8e002!

RNG pin definition fixes are added now as well, thank you again for the bug hunt.
