### ISSUE TITLE
interpolate_multiplier() Index out of bounds

### ISSUE THREAD

**Issue by Matlock42** [connornishijima/SensoryBridge#9]
Bug was introduced on commit e940db4b73b383bcd132bb3d987e4ff92f432051 when `multipliers_smoothed` went from size of `6` => `4`.

The for loop in `fft.h`, line `235` did not get changed to only iterate 4 times.

```
  for (uint8_t i = 0; i < 6; i++) {
    if (multipliers_smoothed[i] < mult_min) {
      mult_min = multipliers_smoothed[i];
    }
  }
```

**Comment by connornishijima** [comment]
Thank you for the catch! Your PR is now merged. :)
